Feature
mesielepush/JS-Testing pull request #1
Opened 2020-07-04 02:00 UTC by mesielepush

Pull request to test my testing abilities on Jest

2020-07-06 07:28 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @mesielepush good job working on this :+1: everything checks out properly except for a little issue with the cipher encryption. 

 - You do want to preserve special characters, so, for example, is there is a . or a - in the word you want to return everything else encrypted except the . and the - still in the right position :slightly_smiling_face: 

**Please make changes and request for another review** :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask:

2020-07-06 07:28 UTC, Oghenebrume50 commented on test/cipher.test.js
> +test('encrypting punctuation', () => {
This should actually be a test that punctuations are kept not encrypted :slightly_smiling_face:

2020-07-06 15:18 UTC, mesielepush commented
Ready no more punctuation ciphering

2020-07-07 02:02 UTC, bellom approved these changes
## Hi @mesielepush  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-07 03:38 UTC, merged